### ISSUE TITLE
Github tags not updated

### ISSUE THREAD

**Issue by jayvdb** [rsalmaso/django-site-metrics#1]
Also it would be nice if there were sdist uploaded to PyPI, including tests, so they can be used for distro packaging.

**Comment by rsalmaso** [comment]
It seems that hg-git don't push tags (anymore?). Good to know.
For sdist maybe, I will check it anyway, but I don't think it is a good idea to package a library which can be updated at will :thinking:

**Comment by jayvdb** [comment]
Thanks for adding the tags.
In production, I prefer stability and reliability of rpms which have a `%check` running the test suiteb before accepting, vs updates from pip & other python packaging tools which are great for dev, but occasionally fail in all sorts of ways.
